version: '3.8'

services:
  # FastAPI service
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../../models:/app/models
      - ../models:/app/code_models
    environment:
      - PYTHONPATH=/app
    networks:
      - admission-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Streamlit web application
  webapp:
    build: ./app
    ports:
      - "8506:8501"
    environment:
      - API_URL=http://api:8000/predict
    depends_on:
      - api
    networks:
      - admission-network
    stdin_open: true
    tty: true

networks:
  admission-network:
    driver: bridge